# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  ci_verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Customer service test
      working-directory: ./Customer
      run: |
        npm ci
        npm test
    
    - name: Product service test
      working-directory: ./Product
      run: |
        npm ci
        npm test
    
    - name: Shopping service test
      working-directory: ./Shopping
      run: |
        npm ci
        npm test
        

